# Application settings available as Rails.application.config.settings
#
# All values in this file are namespaced under Rails.application.config.settings
# and will not conflict with other configuration values in Rails.application.config.
# Settings are manually applied to the correct config var as needed in specific initializers.
# e.g. config/initializers/devise.rb

common: &common
  # Downcased and trimmed app name for namespaces.
  # Safest to start with a letter rather than a number.
  # See locales/en.yml for setting your app's user facing brand name.
  app_name: 'zachary'

  social:
    facebook: 'https://www.facebook.com/kennethcharlesbarrett'
    twitter: 'https://twitter.com/bogusbarrett'
    google_plus: 'https://plus.google.com/+KCBarrett'
    linkedin: 'http://www.linkedin.com/in/'

  contact:
    email: 'kc@example.com'
    phone: '555-555-5555'

  session:
    key: '_starterkit_session'
    expire_after: <%= 30.days %>

  rack:
    # Timeout request after 20 seconds
    timeout: 20

  mail:
    layout: 'emails/email'
    from: 'from@example.com'


# Default ENV vars.
# Set to development values for convenience and override in production by setting ENV on the server.
# As a best practice, do not put production values in this file for security reasons.
default_env: &default_env
  # From address to use when sending email
  MAIL_HOST: 'localhost:3000'

  # Host used to determine direct requests vs CDN.
  # See RobotsController.
  CANONICAL_HOST: 'rails4-starterkit.herokuapp.com'

  AUTH_FACEBOOK_KEY: '201539556694091'
  AUTH_FACEBOOK_SECRET: '80ae1dc93961b7f9a79265af0eeca698'
  AUTH_TWITTER_KEY: 'hbcu8JvAB1FftWw7c3oog'
  AUTH_TWITTER_SECRET: 'uTspycZ4T7QAeA9QLGBb1zoLrR6K7ChBPdYt8F7nZc'

  # Devise password encryption keys.
  # Channging the keys will invalidate user passwords,
  # forcing users to use the forgot password feature.
  # TODO: make new keys with `rake secret`
  DEVISE_SECRET_KEY: '97e3aeb2205334723d6145b3d53a375dd1e73a4025b742d9c4b615fcad05e3285fd124bb7c03f811d7ca08190d338c3de72204dd1905afebc7dfbb282614ae6e'
  DEVISE_PEPPER: 'fd433ea5692d19817ed6eca9086045d629d941f7e4f701bbae57ba60e5ef160e7b03f9bd738627f45e5a533fb9ca845bbd926c7dc41317f52ad32faf5c4cfaee'

  # Signed cookie encryption key.
  # TODO: make new key with `rake secret`
  SECRET_KEY_BASE: '314de9fbc2c08dac328eace7d9c9390e5afd51874e165915ade124e5abc333ceae5035cfbf8f17bf68a3f4d7a220efc1bc8e8e20e10fcdaefcc1cfd2f7b07255'

  # Redis server used by Sidekiq, cache, etc.
  REDIS_URL: 'redis://localhost:6379/0'

  # Airbrake/Errbit configuration
  AIRBRAKE_API_KEY: ''
  AIRBRAKE_HOST: ''


development:
  <<: *common
  env:
    <<: *default_env
    ALLOW_EMAIL_PREVIEW: true

test:
  <<: *common
  env:
    <<: *default_env

staging:
  <<: *common
  env:
    <<: *default_env

production:
  <<: *common
  env:
    # Set dummy key so rake assets:precompile succeeds
    DEVISE_SECRET_KEY: ''
